apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: default
data:
  redis-host: "whoosh-redis.xxxxx.cache.amazonaws.com"
  redis-port: "6379"
  cors-allowed-origins: "https://whoosh.example.com"

